modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="spyglassofcurios"
version="1.2"
displayName="Spyglass of Curios"
logoFile="spyglassofcurioslogo.png"
authors="曦月"
description='''使你的望远镜与饰品栏兼容!'''

[[dependencies.spyglassofcurios]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spyglassofcurios]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spyglassofcurios]]
    modId = "curios"
    mandatory = true
    versionRange = "[1.19.2-5.1.1.0,)"
    ordering = "NONE"
    side = "BOTH"