modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="spyglassofcurios"
version="1.5.1"
displayName="Spyglass of Curios"
logoFile="spyglassofcurioslogo.png"
authors="曦月"
description='''使你的望远镜与饰品栏兼容!'''

[[dependencies.spyglassofcurios]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spyglassofcurios]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spyglassofcurios]]
    modId = "curios"
    mandatory = true
    versionRange = "[5.2.0-beta.3+1.20.1,)"
    ordering = "NONE"
    side = "BOTH"